# Generated by Django 2.2 on 2019-04-08 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('chef_id', models.AutoField(primary_key=True, serialize=False)),
                ('chef_name', models.CharField(max_length=100)),
                ('chef_email', models.EmailField(help_text='Your Email ID', max_length=254)),
                ('chef_mobileNo', models.CharField(help_text='Contact phone number', max_length=10)),
                ('chef_password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Chef',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('customer_mobileNo', models.CharField(help_text='Contact phone number', max_length=10)),
                ('customer_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.FloatField(default=0)),
                ('item_description', models.TextField(max_length=100)),
                ('item_category', models.CharField(max_length=100)),
                ('item_subcategory', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'menuitem',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_no', models.IntegerField()),
                ('item_quantity', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconnection.Customer')),
                ('menuitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconnection.MenuItem')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('c', 'CASH'), ('cr', 'Credit Card'), ('dr', 'Debit Card')], max_length=2)),
                ('amount', models.FloatField(default=0)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconnection.Customer')),
            ],
            options={
                'db_table': 'bill',
            },
        ),
    ]
