# Generated by Django 2.2 on 2019-04-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnection', '0002_currentorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='method',
        ),
        migrations.AddField(
            model_name='currentorder',
            name='customer_id',
            field=models.IntegerField(default=0),
        ),
    ]
