# Generated by Django 2.2 on 2019-04-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnection', '0003_auto_20190408_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=100)),
                ('member_email', models.EmailField(help_text='Your Email ID', max_length=254)),
                ('member_mobileNo', models.CharField(help_text='Contact phone number', max_length=10)),
                ('member_password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
    ]
